### ISSUE TITLE
Telepresence V2 : My DNS is disabled once telepresence connect

### ISSUE THREAD

**Issue by mhdqasim** [telepresenceio/telepresence#1754]
I installed Telepresence V2.2 then after connect By : 

 telepresence connect

I connect to remote cluster but My DNS is overridden by telepresence and not able to see it

**Comment by thallgren** [comment]
Hi @mhdqasim . Can you please try the 2.3.0 version? It should resolve this issue.

**Comment by akharlamov** [comment]
I have the same issue with telepresence 2.3.4/Ubuntu 20.04.2

After `telepresence connect`, I can resolve FQDNs in the Kubernetes cluster. But all external domains are not resolved.
> host mysql.dev2         
mysql.dev2 has address 10.106.220.114
> host www.google.com
;; connection timed out; no servers could be reached

I was able to intercept DNS traffic with Wireshark on the loopback interface. 
I see 127.0.0.1->127.0.0.53 request and systemd-resolver responds with a properly resolved reply back. But it seems telepresence daemon do not get the reply. 

The logs are full of timeout messages:
```
2021/07/16 07:58:12.6397 error   daemon/server-dns/legacy : read udp 127.0.0.1:34380->127.0.0.53:53: i/o timeout (from pkg/client/daemon/dns/dns.go:114)
2021/07/16 07:58:12.6398 error   daemon/server-dns/legacy : read udp 127.0.0.1:34380->127.0.0.53:53: i/o timeout (from pkg/client/daemon/dns/dns.go:114)
2021/07/16 07:58:12.6398 error   daemon/server-dns/legacy : read udp 127.0.0.1:34380->127.0.0.53:53: i/o timeout (from pkg/client/daemon/dns/dns.go:114)
2021/07/16 07:58:12.6398 error   daemon/server-dns/legacy : read udp 127.0.0.1:34380->127.0.0.53:53: i/o timeout (from pkg/client/daemon/dns/dns.go:114)
2021/07/16 07:58:12.6398 error   daemon/server-dns/legacy : read udp 127.0.0.1:34380->127.0.0.53:53: i/o timeout (from pkg/client/daemon/dns/dns.go:114)
```

Another interesting log snippet refers to failure to initialise systemd-resolved. Indeed Ubuntu 20.04 uses systemd-resolved.
```
021/07/16 07:57:47.4744 info    daemon/server-grpc : gRPC server started (from pkg/client/daemon/service.go:207)
2021/07/16 07:58:03.7183 info    daemon/watch-cluster-info : Adding service subnet 10.96.0.0/12 (from pkg/client/daemon/tunrouter.go:256)
2021/07/16 07:58:03.7183 info    daemon/watch-cluster-info : Adding pod subnet 10.244.0.0/24 (from pkg/client/daemon/tunrouter.go:262)
2021/07/16 07:58:03.7189 info    daemon/watch-cluster-info : started command ["ip" "a" "add" "10.96.0.0/12" "dev" "tel0"] : dexec.pid="54648"
2021/07/16 07:58:03.7192 info    daemon/watch-cluster-info :  : dexec.pid="54648" dexec.stream="stdin" dexec.err="EOF"
2021/07/16 07:58:03.7217 info    daemon/watch-cluster-info : finished successfully: exit status 0 : dexec.pid="54648"
2021/07/16 07:58:03.7222 info    daemon/watch-cluster-info : started command ["ip" "a" "add" "10.244.0.0/24" "dev" "tel0"] : dexec.pid="54651"
2021/07/16 07:58:03.7223 info    daemon/watch-cluster-info :  : dexec.pid="54651" dexec.stream="stdin" dexec.err="EOF"
2021/07/16 07:58:03.7240 info    daemon/watch-cluster-info : finished successfully: exit status 0 : dexec.pid="54651"
2021/07/16 07:58:03.7397 info    daemon/server-dns/resolved/Server : Configuring DNS IP 10.96.0.10 (from pkg/client/daemon/resolved_linux.go:88)
2021/07/16 07:58:04.7400 error   daemon/server-dns/resolved/SanityCheck : resolver did not receive requests from systemd-resolved (from pkg/client/daemon/resolved_linux.go:122)
2021/07/16 07:58:04.7402 error   daemon/server-dns/resolved/SanityCheck : goroutine "/daemon/server-dns/resolved/SanityCheck" exited with error: resolved not configured
2021/07/16 07:58:04.7402 info    daemon/server-dns/resolved/Server:shutdown_logger : shutting down (gracefully)...
2021/07/16 07:58:04.7402 info    daemon/server-dns/resolved:shutdown_logger : shutting down (gracefully)...
2021/07/16 07:58:04.7403 info    daemon/server-dns/resolved:shutdown_status :   final goroutine statuses:
2021/07/16 07:58:04.7410 info    daemon/server-dns/resolved:shutdown_status :     /daemon/server-dns/resolved/SanityCheck: exited with error
2021/07/16 07:58:04.7410 info    daemon/server-dns/resolved:shutdown_status :     /daemon/server-dns/resolved/Server     : exited without error
2021/07/16 07:58:04.7411 info    daemon/server-dns : Unable to use systemd-resolved, falling back to local server (from pkg/client/daemon/outbound_linux.go:33)
```

```
> sudo iptables -t nat -L 
[sudo] password for aih1013: 
Chain PREROUTING (policy ACCEPT)
target     prot opt source               destination         
DOCKER     all  --  anywhere             anywhere             ADDRTYPE match dst-type LOCAL

Chain INPUT (policy ACCEPT)
target     prot opt source               destination         

Chain OUTPUT (policy ACCEPT)
target     prot opt source               destination         
telepresence-dns  all  --  anywhere             anywhere            
DOCKER     all  --  anywhere            !127.0.0.0/8          ADDRTYPE match dst-type LOCAL

Chain POSTROUTING (policy ACCEPT)
target     prot opt source               destination         
MASQUERADE  all  --  172.17.0.0/16        anywhere            
MASQUERADE  all  --  172.18.0.0/16        anywhere            
MASQUERADE  all  --  172.19.0.0/16        anywhere            
LIBVIRT_PRT  all  --  anywhere             anywhere            

Chain DOCKER (2 references)
target     prot opt source               destination         
RETURN     all  --  anywhere             anywhere            
RETURN     all  --  anywhere             anywhere            
RETURN     all  --  anywhere             anywhere            

Chain LIBVIRT_PRT (1 references)
target     prot opt source               destination         
RETURN     all  --  192.168.122.0/24     224.0.0.0/24        
RETURN     all  --  192.168.122.0/24     255.255.255.255     
MASQUERADE  tcp  --  192.168.122.0/24    !192.168.122.0/24     masq ports: 1024-65535
MASQUERADE  udp  --  192.168.122.0/24    !192.168.122.0/24     masq ports: 1024-65535
MASQUERADE  all  --  192.168.122.0/24    !192.168.122.0/24    

Chain telepresence-dns (1 references)
target     prot opt source               destination         
RETURN     udp  --  localhost            anywhere             udp spt:34380
REDIRECT   udp  --  anywhere             127.0.0.53           udp dpt:domain redir ports 35912
 aih1013@pirate  ~/.cache/telepresence/logs  sudo iptables -t filter -L 
Chain INPUT (policy ACCEPT)
target     prot opt source               destination         
LIBVIRT_INP  all  --  anywhere             anywhere            

Chain FORWARD (policy ACCEPT)
target     prot opt source               destination         
DOCKER-USER  all  --  anywhere             anywhere            
DOCKER-ISOLATION-STAGE-1  all  --  anywhere             anywhere            
ACCEPT     all  --  anywhere             anywhere             ctstate RELATED,ESTABLISHED
DOCKER     all  --  anywhere             anywhere            
ACCEPT     all  --  anywhere             anywhere            
ACCEPT     all  --  anywhere             anywhere            
ACCEPT     all  --  anywhere             anywhere             ctstate RELATED,ESTABLISHED
DOCKER     all  --  anywhere             anywhere            
ACCEPT     all  --  anywhere             anywhere            
ACCEPT     all  --  anywhere             anywhere            
ACCEPT     all  --  anywhere             anywhere             ctstate RELATED,ESTABLISHED
DOCKER     all  --  anywhere             anywhere            
ACCEPT     all  --  anywhere             anywhere            
ACCEPT     all  --  anywhere             anywhere            
LIBVIRT_FWX  all  --  anywhere             anywhere            
LIBVIRT_FWI  all  --  anywhere             anywhere            
LIBVIRT_FWO  all  --  anywhere             anywhere            

Chain OUTPUT (policy ACCEPT)
target     prot opt source               destination         
LIBVIRT_OUT  all  --  anywhere             anywhere            

Chain DOCKER (3 references)
target     prot opt source               destination         

Chain DOCKER-ISOLATION-STAGE-1 (1 references)
target     prot opt source               destination         
DOCKER-ISOLATION-STAGE-2  all  --  anywhere             anywhere            
DOCKER-ISOLATION-STAGE-2  all  --  anywhere             anywhere            
DOCKER-ISOLATION-STAGE-2  all  --  anywhere             anywhere            
RETURN     all  --  anywhere             anywhere            

Chain DOCKER-ISOLATION-STAGE-2 (3 references)
target     prot opt source               destination         
DROP       all  --  anywhere             anywhere            
DROP       all  --  anywhere             anywhere            
DROP       all  --  anywhere             anywhere            
RETURN     all  --  anywhere             anywhere            

Chain DOCKER-USER (1 references)
target     prot opt source               destination         
RETURN     all  --  anywhere             anywhere            

Chain LIBVIRT_FWI (1 references)
target     prot opt source               destination         
REJECT     all  --  anywhere             anywhere             reject-with icmp-port-unreachable
ACCEPT     all  --  anywhere             192.168.122.0/24     ctstate RELATED,ESTABLISHED
REJECT     all  --  anywhere             anywhere             reject-with icmp-port-unreachable

Chain LIBVIRT_FWO (1 references)
target     prot opt source               destination         
REJECT     all  --  anywhere             anywhere             reject-with icmp-port-unreachable
ACCEPT     all  --  192.168.122.0/24     anywhere            
REJECT     all  --  anywhere             anywhere             reject-with icmp-port-unreachable

Chain LIBVIRT_FWX (1 references)
target     prot opt source               destination         
ACCEPT     all  --  anywhere             anywhere            
ACCEPT     all  --  anywhere             anywhere            

Chain LIBVIRT_INP (1 references)
target     prot opt source               destination         
ACCEPT     udp  --  anywhere             anywhere             udp dpt:domain
ACCEPT     tcp  --  anywhere             anywhere             tcp dpt:domain
ACCEPT     udp  --  anywhere             anywhere             udp dpt:bootps
ACCEPT     tcp  --  anywhere             anywhere             tcp dpt:67
ACCEPT     udp  --  anywhere             anywhere             udp dpt:domain
ACCEPT     tcp  --  anywhere             anywhere             tcp dpt:domain
ACCEPT     udp  --  anywhere             anywhere             udp dpt:bootps
ACCEPT     tcp  --  anywhere             anywhere             tcp dpt:67

Chain LIBVIRT_OUT (1 references)
target     prot opt source               destination         
ACCEPT     udp  --  anywhere             anywhere             udp dpt:domain
ACCEPT     tcp  --  anywhere             anywhere             tcp dpt:domain
ACCEPT     udp  --  anywhere             anywhere             udp dpt:bootpc
ACCEPT     tcp  --  anywhere             anywhere             tcp dpt:68
ACCEPT     udp  --  anywhere             anywhere             udp dpt:domain
ACCEPT     tcp  --  anywhere             anywhere             tcp dpt:domain
ACCEPT     udp  --  anywhere             anywhere             udp dpt:bootpc
ACCEPT     tcp  --  anywhere             anywhere             tcp dpt:68
```

**Comment by thallgren** [comment]
@mhdqasim can you please enable [debug logging](https://www.telepresence.io/docs/latest/reference/config/#log-levels) for the rootDaemon and provide the `daemon.log` down to the point where the timeouts start.

**Comment by akharlamov** [comment]
Attaching the log with DEBUG enabled. The file is produced by the latest version from release/v2 branch.
[daemon.log.gz](https://github.com/telepresenceio/telepresence/files/6833295/daemon.log.gz)

**Comment by thallgren** [comment]
Please try the new 2.3.7 release. It contains some improvements for the `systemd-resolved` based DNS resolver that I think might fix the problem reported here. It would be great to get that verified.

**Comment by daviddawson** [comment]
Hello, I have been tracking this problem for while. I can confirm that Telepresence version 2.3.7 resolves the names given out by the Strimzi managed bootstrap server, and the IP is correct.  The IP it is resolving though is not routeable from outside the cluster for me.

OS: Ubuntu 20.10
Systemd: 246
Kubernetes: Kind[v0.11.1], Cluster: v1.21.1
Docker: 20.10.7, build f0df350

```
ping kafka-kafka-0.kafka-kafka-brokers.myapp.svc
PING kafka-kafka-0.kafka-kafka-brokers.myapp.svc (172.17.0.16) 56(84) bytes of data.
^C
--- kafka-kafka-0.kafka-kafka-brokers.myapp.svc ping statistics ---
2 packets transmitted, 0 received, 100% packet loss, time 1015ms
```

The IP above is my main docker bridge subnet - 172.17.0.0/24
The Cluster IPs within Kind are all in 10.244.0.0/24. 
The docker bridge that the wrapping Kind container is using is 172.19.0.2.  Kubenetes daemonset pods bind to that IP.

I actually can't see any references to 172.17.0.0/24 inside kubernetes anywhere.  It does resolve properly within the cluster though.

**Comment by akharlamov** [comment]
2.3.7 does not work for me still. However, I have pinpointed the root issue. On my machine, the defaultroute interface is configure with `~.` domain. Hence, when tel2 runs sanity check, the DNS request is still routed to the old DNS server. 

Please, see PR  #1920 for the fix.

**Comment by naty88** [comment]
Hi, i have a very similar issue both with Telepresence v2.6.8 and v2.8.5.
[daemon+connector.log.zip](https://github.com/telepresenceio/telepresence/files/9943787/daemon%2Bconnector.log.zip)

Here is the output from `telepresence status`:
```Root Daemon: Running
  Version   : v2.8.5 (api 3)
  DNS       :
    Local IP        : 127.0.0.53
    Remote IP       : <nil>
    Exclude suffixes: [.com .io .net .org .ru .fritz.box]
    Include suffixes: []
    Timeout         : 8s
  Also Proxy : (0 subnets)
  Never Proxy: (2 subnets)
    - 3.126.58.64/32
    - 35.157.197.134/32
User Daemon: Running
  Version         : v2.8.5 (api 3)
  Executable      : /usr/local/bin/telepresence
  Install ID      : 1eaaec51-1c1a-4e02-b639-0dd304a0cfe7
  Ambassador Cloud:
    Status      : Logged out
    User ID     : 
    Account ID  : 
    User Name   : 
    Email       : 
    Account Name: 
  Status            : Connected
  Kubernetes server : https://2CFB153CF5899CA42817C18674F2D2DD.yl4.eu-central-1.eks.amazonaws.com
  Kubernetes context: staging
  Intercepts        : 0 total
```

**Comment by thallgren** [comment]
@naty88 please create a new ticket. The fact that you have similar problems doesn't mean that it's the same problem.
