### ISSUE TITLE
Telepresence connect breaks the DNS settings if host is on VPN

### ISSUE THREAD

**Issue by tanersener** [telepresenceio/telepresence#2165]
**Describe the bug**
The latest version v2.4.5 works well when I'm not on VPN. But, if I run `telepresence connect` after connecting to VPN, then my VPN specific DNS settings are being reverted to my non-VPN settings. Additionally, `telepresence connect` doesn't fail but `telepresence intercept whoami` command I run after that fails.

I looked at #2085 and #2143 too. I believe my case is different than those. I don't see an issue about the subnets. 

**To Reproduce**

0. When I'm not on VPN, this is what I have in my `/etc/resolv.conf`

```
nameserver 127.0.0.53
options edns0 trust-ad
search cluster.local
```

1. After connecting to VPN, this is what my `/etc/resolv.conf` becomes

```
search mycompany.com
nameserver 10.xxx.xxx.xxx
nameserver 10.xxx.xxx.xxx
```

2. When I run `telepresence connect` I don't see any errors

```
Launching Telepresence Root Daemon
Launching Telepresence User Daemon
Connected to context kind-cluster (https://127.0.0.1:40813)
```

But the content of my `/etc/resolv.conf` returns to its pre-VPN state. Therefore, I can't access to anything from my computer

```
nameserver 127.0.0.53
options edns0 trust-ad
search cluster.local
```

3. If I ignore this and run `telepresence intercept` then `telepresence` fails and asks me to create a bug ticket

```
telepresence intercept whoami
telepresence: error: Failed to establish intercept: found no services with a selector matching labels map[app:whoami] in namespace default

See logs for details (1 error found): "/home/tanersener/.cache/telepresence/logs/connector.log"
If you think you have encountered a bug, please run `telepresence gather-logs` and attach the telepresence_logs.zip to your github issue or create a new one: https://github.com/telepresenceio/telepresence/issues/new?template=Bug_report.md .
```

4. So I look at `daemon.log` and see those DNS timeouts, which I believe are quite normal

`2021-10-20 17:35:46.0889 info    daemon/background-metriton : scout report "incluster_dns_query" failed: Post "https://metriton.datawire.io/scout": dial tcp: lookup metriton.datawire.io on 127.0.0.53:53: read udp 127.0.0.1:46939->127.0.0.53:53: i/o timeout`

5. `connector.log` doesn't have big issues. Below you can see my routing table as well. I masked my gateway with `x`. `gpd0` is my VPN, `tel0` is telepresence

- Before `telepresence connect`

```
Kernel IP routing table
Destination     Gateway         Genmask         Flags   MSS Window  irtt Iface
0.0.0.0         172.122.xxx.xx  0.0.0.0         UG        0 0          0 gpd0
0.0.0.0         192.168.3.1     0.0.0.0         UG        0 0          0 wlp3s0
10.122.14.20    172.122.xxx.xx  255.255.255.255 UGH       0 0          0 gpd0
10.192.14.20    172.122.xxx.xx  255.255.255.255 UGH       0 0          0 gpd0
80.87.19.178    192.168.3.1     255.255.255.255 UGH       0 0          0 wlp3s0
169.254.0.0     0.0.0.0         255.255.0.0     U         0 0          0 virbr0
172.17.0.0      0.0.0.0         255.255.0.0     U         0 0          0 docker0
172.21.0.0      0.0.0.0         255.255.0.0     U         0 0          0 br-7799b043c475
192.168.3.0     0.0.0.0         255.255.255.0   U         0 0          0 wlp3s0
192.168.122.0   0.0.0.0         255.255.255.0   U         0 0          0 virbr0
```

- After `telepresence connect`
```
Kernel IP routing table
Destination     Gateway         Genmask         Flags   MSS Window  irtt Iface
0.0.0.0         172.122.xxx.xx  0.0.0.0         UG        0 0          0 gpd0
0.0.0.0         192.168.3.1     0.0.0.0         UG        0 0          0 wlp3s0
10.96.0.0       0.0.0.0         255.255.0.0     U         0 0          0 tel0
10.122.14.20    172.122.xxx.xx  255.255.255.255 UGH       0 0          0 gpd0
10.192.14.20    172.122.xxx.xx  255.255.255.255 UGH       0 0          0 gpd0
10.244.0.0      0.0.0.0         255.255.255.0   U         0 0          0 tel0
10.244.1.0      0.0.0.0         255.255.255.0   U         0 0          0 tel0
10.244.2.0      0.0.0.0         255.255.255.0   U         0 0          0 tel0
80.87.19.178    192.168.3.1     255.255.255.255 UGH       0 0          0 wlp3s0
169.254.0.0     0.0.0.0         255.255.0.0     U         0 0          0 virbr0
172.17.0.0      0.0.0.0         255.255.0.0     U         0 0          0 docker0
172.21.0.0      0.0.0.0         255.255.0.0     U         0 0          0 br-7799b043c475
192.168.3.0     0.0.0.0         255.255.255.0   U         0 0          0 wlp3s0
192.168.122.0   0.0.0.0         255.255.255.0   U         0 0          0 virbr0
```

**Expected behavior**
Being able to run `telepresence intercept` with no issues when I'm on VPN

**Versions:**
 - Output of `telepresence version`
 ```
 telepresence version
Client: v2.4.5 (api v3)
Root Daemon: v2.4.5 (api v3)
User Daemon: v2.4.5 (api v3)
```
  
 - Operating system of workstation running `telepresence` commands: `Ubuntu 20.04.3 LTS`

 - Kubernetes environment and Version: `kind`
 ```
kubectl version
Client Version: version.Info{Major:"1", Minor:"21", GitVersion:"v1.21.3", GitCommit:"ca643a4d1f7bfe34773c74f79527be4afd95bf39", GitTreeState:"clean", BuildDate:"2021-07-15T21:04:39Z", GoVersion:"go1.16.6", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"20", GitVersion:"v1.20.7", GitCommit:"132a687512d7fb058d0f5890f07d4121b3f0a2e2", GitTreeState:"clean", BuildDate:"2021-05-27T23:27:49Z", GoVersion:"go1.15.12", Compiler:"gc", Platform:"linux/amd64"}
```

**Additional context**
- This is the output of `telepresence status`
```
telepresence status
Root Daemon: Running
  Version   : v2.4.5 (api 3)
  DNS       :
    Remote IP       : 10.96.0.10
    Exclude suffixes: [.arpa .com .io .net .org .ru]
    Include suffixes: []
    Timeout         : 4s
  Also Proxy: (0 subnets)
User Daemon: Running
  Version           : v2.4.5 (api 3)
  Ambassador Cloud  : Logged out
  Status            : Connected
  Kubernetes server : https://127.0.0.1:40813
  Kubernetes context: kind-cluster
  Telepresence proxy: ON (networking to the cluster is enabled)
  Intercepts        : 0 total
```

- Logs collected by `telepresence gather-logs`: [telepresence_logs.zip](https://github.com/telepresenceio/telepresence/files/7383163/telepresence_logs.zip)

**Comment by elig-salt** [comment]
I think we're having the same problem, using a VPN - and recently Telepresence just stopped working.. couldn't even curl to https://kubernetes.default after `telepresence connect`

**Comment by tmotley** [comment]
+1

We are seeing this behavior too 😞

**Comment by zrks** [comment]
experiencing this same issue on `v2.4.9` - are there some workarounds/fixes for this?

**Comment by flerpo** [comment]
+1

**Comment by zrks** [comment]
just to report back - for me version `v2.4.10` doesn't break vpn, but now I have other issues

**Comment by elig-salt** [comment]
For us - this was resolved by making sure the CIDR (IP Range) of pods on Kubernetes was not included / overlapping with CIDR pushed to our clients by VPN.

This just means that when developers run `telepresence intercept` - it will tell the machine to send all traffic directed at the namespace - to the daemon itself, which sends it's traffic in-turn into the traffic-manager in kubernetes.

If the VPN tries to direct that traffic to the VPN machine, the telepresence agent can't work properly.

From what I've seen - most problems people have with VPN is usually related to this issue.

I hope that helps @tanersener

**Comment by tanersener** [comment]
I still have this issue on `v2.4.10`.

@elig-salt I don't see any overlapping ranges in my routing table. I also don't understand how that can explain my `/etc/resolv.conf` file being overridden to its pre-VPN state.

**Comment by vanlongme** [comment]
have same issue at v2.5

**Comment by thallgren** [comment]
This is surprising. AFAIK, Telepresence doesn't do anything to modify the /etc/resolv.conf file. @tanersener is your system using `systemd-resolved`?

**Comment by thallgren** [comment]
@vanlongme are you also seeing modifications to the `/etc/resolv.conf` file? What 2.5 version are you using, and on what platform? What does `telepresence test-vpn` tell you?

**Comment by tanersener** [comment]
@thallgren Yeah, I'm on `Ubuntu 20.04`. It has `systemd-resolved` running. I can try disabling it if that's causing this issue.

**Comment by cindymullins-dw** [comment]
Looking to close this issue if resolved.  Are there still instances of Telepresence modifying the `/etc/resolv.conf`, as I believe that's the remaining question.

**Comment by tanersener** [comment]
@cindymullins-dw I don't have access to this environment anymore. I don't mind if the issue is closed. The issue was never resolved btw.

**Comment by thallgren** [comment]
I'm closing this because we've improved several things in this area. Feel free to open a new issue if you have problems with a specific VPN together with Kind clusters.
