### ISSUE TITLE
Telepresense failing on Apple M1 Processor

### ISSUE THREAD

**Issue by dpkemarsys** [telepresenceio/telepresence#2396]
### What were you trying to do?

(please tell us)

### What did you expect to happen?

(please tell us)

### What happened instead?

(please tell us - the traceback is automatically included, see below.
use https://gist.github.com to pass along full telepresence.log)

### Automatically included information

Command line: `['/opt/homebrew/bin/telepresence', '--container-to-host', '9001', '--mount=/tmp/5daa1a0fe7', '--swap-deployment', 'project-generic-trustpilot-web', '--namespace', 'project-generic-trustpilot', '--expose', '80', '--docker-run', '--rm', '-it', '-v', '/Users/deepakoberoi/sap/ems-cd-project-generic-trustpilot:/var/www', '-v=/tmp/5daa1a0fe7/mnt:/mnt', '-e', 'APP_ENV=telepresence', '-e', 'TELEPRESENCE_PASSWORD=f4898b32a3dcc60c39baa5e380832bbac30cd49c6ce12430a05504dc7b15a3ce', 'project-generic-trustpilot-web']`
Version: `0.109`
Python version: `3.9.10 (main, Jan 15 2022, 11:40:53) 
[Clang 13.0.0 (clang-1300.0.29.3)]`
kubectl version: `Client Version: v1.23.3 // Server Version: v1.22.4`
oc version: `(error: [Errno 2] No such file or directory: 'oc')`
OS: `Darwin FVFH1367Q05N 21.3.0 Darwin Kernel Version 21.3.0: Wed Jan  5 21:37:58 PST 2022; root:xnu-8019.80.24~20/RELEASE_ARM64_T8101 arm64`

```
Traceback (most recent call last):
  File "/opt/homebrew/bin/telepresence/telepresence/cli.py", line 135, in crash_reporting
    yield
  File "/opt/homebrew/bin/telepresence/telepresence/main.py", line 81, in main
    user_process = launch(
  File "/opt/homebrew/bin/telepresence/telepresence/outbound/setup.py", line 157, in launch
    return run_docker_command(
  File "/opt/homebrew/bin/telepresence/telepresence/outbound/container.py", line 195, in run_docker_command
    runner.check_call(
  File "/opt/homebrew/bin/telepresence/telepresence/runner/runner.py", line 458, in check_call
    self._run_command_sync(
  File "/opt/homebrew/bin/telepresence/telepresence/runner/runner.py", line 437, in _run_command_sync
    raise CalledProcessError(
subprocess.CalledProcessError: Command '['docker', 'run', '--network=container:telepresence-1644936345-543092-3352', '--rm', 'datawire/telepresence-local:0.109', 'wait']' returned non-zero exit status 1.

```

Logs:

```
 | [30] Launching Local SSH port forward: ssh -N -oServerAliveInterval=1 -oServerAliveCountMax=10 -F /dev/null -oStrictHostKeyChecking=no -oUserKnownHostsFile=/dev/null -oConnectTimeout=5 -q -p 49717 root@127.0.0.1 -R 38023:127.0.0.1:49699 -R 9001:127.0.0.1:9001
  23.6 TEL | [31] Running: docker run --network=container:telepresence-1644936345-543092-3352 --rm datawire/telepresence-local:0.109 wait
  23.7  31 | WARNING: The requested image's platform (linux/amd64) does not match the detected host platform (linux/arm64/v8) and no specific platform was requested
  23.8  31 | [INFO  tini (1)] Spawned child process 'python3' with pid '9'
  44.1 TEL | [32] Running: sudo -n echo -n
  44.2 TEL | [32] ran in 0.05 secs.
  49.7 TEL | (proxy checking local liveness)
  49.9  15 | 2022-02-15T14:46:13+0000 [Poll#info] Checkpoint
  55.2  31 | Failed to connect to proxy in remote cluster.
  55.3  31 | [INFO  tini (1)] Main child exited normally (with status '1')
  55.3 TEL | [31] exit 1 in 31.76 secs.

```

**Comment by techiemac** [comment]
Hey @dpkemarsys this is the same as https://github.com/telepresenceio/telepresence/issues/1556. I have a fix pushed to our fork that I'm testing right now.

**Comment by techiemac** [comment]
FYI, the branch is here but this is very specific to us and still needs quite a bit of testing so fair warning 😉 https://github.com/getbread/telepresence/tree/TOOLS-333-implement-m-1-support-in-telepresence

Also, if you can, I highly recommend moving to v2. One of the big and soon to be upcoming features is multiport intercept support which the telepresence team is working on and I know it's holding a few people back from going to v2.

**Comment by cindymullins-dw** [comment]
v1 is deprecated.  Please reopen if issue persists on the [latest versions](https://www.getambassador.io/docs/telepresence/latest/install).
