### ISSUE TITLE
unable to get route for never-proxied subnet <kube-api-server-ip>

### ISSUE THREAD

**Issue by rajetta** [telepresenceio/telepresence#2502]
**Describe the bug**

I see this error message in daemon log:
  unable to get route for never-proxied subnet 130.35.146.1/32. If this is your kubernetes API server you may want to open an issue, since telepresence may not work if it falls within the CIDR for pods/services. 

I can resolve the service by name after I do `telepresence connect`, however I can't connect to it. 

**To Reproduce**
1. When I run `telepresence connect`
2. I see `unable to get route for never-proxied subnet 130.35.146.1/32`
3. cat 'daemon.log'
```
2022-04-04 20:57:20.4236 info    daemon/session : Connected to Manager 2.5.4
2022-04-04 20:57:20.4627 error   daemon/session : unable to get route for never-proxied subnet 130.35.146.1/32. If this is your kubernetes API server you may want to open an issue, since telepresence may not work if it falls within the CIDR for pods/services. Error: gateway:\s+([0-9.]+)\s+.*interface:\s+([a-z0-9]+) did not match output of route:
   route to: 130.35.146.1
destination: default
       mask: default
  interface: utun3
      flags: <UP,DONE,CLONING,STATIC,GLOBAL>
 recvpipe  sendpipe  ssthresh  rtt,msec    rttvar  hopcount      mtu     expire
       0         0         0         0         0         0      1300         0
```
**Expected behavior**
Be able to connect any service with `curl <service-name>:<port>`. Instead, connection times out. 

**Versions (please complete the following information):**
 - Output of `telepresence version`
 ```
 telepresence version
Client: v2.5.4 (api v3)
Root Daemon: v2.5.4 (api v3)
User Daemon: v2.5.4 (api v3)
```
 - Operating system of workstation running `telepresence` commands
 MacOS Monterey arm64 
 - Kubernetes environment and Version [e.g. Minikube, bare metal, Google Kubernetes Engine]
` Container Engine for Kubernetes - OKE. "v1.21.5"`
**VPN-related bugs:**
If you're reporting an issue around telepresence connectivity when using a VPN,
and are running Telepresence 2.4.8 or above, please also attach the output
of `telepresence test-vpn`, and the following information:
```
telepresence test-vpn
Telepresence Network disconnecting...done
Telepresence Traffic Manager disconnecting...done
Please disconnect from your VPN now and hit enter once you're disconnected...

Please connect to your VPN now and hit enter once you're connected...

telepresence: error: timed out waiting for a route to 8.8.8.8; this usually means your VPN client is misconfigured
```
**Note: I don't have the option to configure any options in the client**

 - Which VPN client are you using? Cisco AnyConnect mobile secure client
 - Which VPN server are you using? Cisco 
 - How is your VPN pushing DNS configuration? It may be useful to add the contents of /etc/resolv.conf
```
#
# macOS Notice
#
# This file is not consulted for DNS hostname resolution, address
# resolution, or the DNS query routing mechanism used by most
# processes on this system.
#
# To view the DNS configuration used by this system, use:
#   scutil --dns
#
# SEE ALSO
#   dns-sd(1), scutil(8)
#
# This file is automatically generated.
#
search us.oracle.com
nameserver 2606:B400:300:D:FEED::1
nameserver 2606:B400:300:D:FEED::2
nameserver 206.223.27.1
nameserver 206.223.27.2
```
**Additional context**
There are no other errors in connector.log and I can see the pod replaced (with 2 containers - one running the agent). I can also get requests into my local instance, but the outgoing connection doesn't work. DNS is resolved. I am quite positive it is related to my VPN setup, but not sure how to fix.

**Comment by thallgren** [comment]
This is probably fixed in #2505 so please try our nightly once that PR has been merged.

**Comment by rajetta** [comment]
@thallgren  with 2.5.8, I  no longer see errors when I run `telepresece connect` or `test-vpn` command.  However, DNS is still broken - I am not able to resolve the service name. We can close the issue as original reporter bug is fixed
