### ISSUE TITLE
Command `telepresence helm install` not obeying value overrides

### ISSUE THREAD

**Issue by thecooldrop** [telepresenceio/telepresence#3642]
**Describe the bug**
When installing Telepresence Helm chart using the Telepresence CLI, with `telepresence helm install` command the overrides for Helm values provided by `--set` and `-f` flags do not seem to be obeyed.

I have had issues with securityContext when trying to debug ArgoCD, because ArgoCD securityContext is overly restricted and the sidecar container fails to start as root user. I tried installing the Telepresence with `telepresence helm install --set agent.securityContext={}` and with `telepresence helm install --set agent.securityContext=null`, but in every case the values are not obeyed, and the Deployment for `traffic-manager` does not include the environment variables for overriding the agent security context.

To reproduce the bug you can use following values file:

> values.yaml

```yaml
agent:
  securityContext: 
    allowPrivilegeEscalation: true
    runAsNonRoot: false
```

When we then run `telepresence helm install -f values.yaml` then Telepresence gets installed with following Deployment in namespace `ambassador`:

> kubectl describe deployments -n ambassador traffic-manager
```
Name:                   traffic-manager
Namespace:              ambassador
CreationTimestamp:      Mon, 08 Jul 2024 18:35:52 +0200
Labels:                 app=traffic-manager
                        app.kubernetes.io/created-by=Helm
                        app.kubernetes.io/managed-by=Helm
                        app.kubernetes.io/version=2.19.0
                        helm.sh/chart=telepresence-2.19.0
                        telepresence=manager
Annotations:            deployment.kubernetes.io/revision: 1
                        meta.helm.sh/release-name: traffic-manager
                        meta.helm.sh/release-namespace: ambassador
Selector:               app=traffic-manager,telepresence=manager
Replicas:               1 desired | 1 updated | 1 total | 1 available | 0 unavailable
StrategyType:           RollingUpdate
MinReadySeconds:        0
RollingUpdateStrategy:  25% max unavailable, 25% max surge
Pod Template:
  Labels:           app=traffic-manager
                    telepresence=manager
  Service Account:  traffic-manager
  Containers:
   traffic-manager:
    Image:       docker.io/datawire/tel2:2.19.0
    Ports:       8081/TCP, 443/TCP
    Host Ports:  0/TCP, 0/TCP
    Environment:
      LOG_LEVEL:                    info
      REGISTRY:                     docker.io/datawire
      SERVER_PORT:                  8081
      POD_CIDR_STRATEGY:            auto
      MUTATOR_WEBHOOK_PORT:         443
      AGENT_INJECTOR_SECRET:        mutator-webhook-tls
      GRPC_MAX_RECEIVE_SIZE:        4Mi
      AGENT_ARRIVAL_TIMEOUT:        30s
      AGENT_INJECT_POLICY:          OnDemand
      AGENT_INJECTOR_NAME:          agent-injector
      AGENT_PORT:                   9900
      AGENT_APP_PROTO_STRATEGY:     http2Probe
      AGENT_IMAGE_PULL_POLICY:      IfNotPresent
      PROMETHEUS_PORT:              0
      MANAGER_NAMESPACE:             (v1:metadata.namespace)
      POD_IP:                        (v1:status.podIP)
      CLIENT_CONNECTION_TTL:        24h
      CLIENT_DNS_EXCLUDE_SUFFIXES:  .com .io .net .org .ru
    Mounts:                         <none>
  Volumes:                          <none>
Conditions:
  Type           Status  Reason
  ----           ------  ------
  Available      True    MinimumReplicasAvailable
  Progressing    True    NewReplicaSetAvailable
OldReplicaSets:  <none>
NewReplicaSet:   traffic-manager-f658f7fc (1/1 replicas created)
Events:
  Type    Reason             Age   From                   Message
  ----    ------             ----  ----                   -------
  Normal  ScalingReplicaSet  86s   deployment-controller  Scaled up replica set traffic-manager-f658f7fc to 1
```

Additionally, if you are using Telepresence 2.4.4 and above, please use
`telepresence loglevel debug` to ensure we have the most helpful logs,
reproduce the error, and then run `telepresence gather-logs` to create a
zip file of all logs for Telepresence's components (root and user daemons,
traffic-manager, and traffic-agents) and attach it to this issue. See an
example command below:
```
telepresence loglevel debug

* reproduce the error *

telepresence gather-logs --output-file /tmp/telepresence_logs.zip

# To see all options, run the following command
telepresence gather-logs --help
```

Here you can see that environment variable `AGENT_SECURITY_CONTEXT` is not configured for the Deployment, as it should be according to the current version of Helm chart.

Side-information about Telepresence:
 
> telepresence version
```
OSS Client     : v2.19.0
OSS Root Daemon: v2.19.0
OSS User Daemon: v2.19.0
Traffic Manager: not connected
```

> kubectl version -o yaml
```yaml
clientVersion:
  buildDate: "2022-05-24T12:26:19Z"
  compiler: gc
  gitCommit: 3ddd0f45aa91e2f30c70734b175631bec5b5825a
  gitTreeState: clean
  gitVersion: v1.24.1
  goVersion: go1.18.2
  major: "1"
  minor: "24"
  platform: linux/amd64
kustomizeVersion: v4.5.4
serverVersion:
  buildDate: "2024-02-14T22:24:00Z"
  compiler: gc
  gitCommit: 4b8e819355d791d96b7e9d9efe4cbafae2311c88
  gitTreeState: clean
  gitVersion: v1.29.2
  goVersion: go1.21.7
  major: "1"
  minor: "29"
  platform: linux/amd64
```

> kind version:
```
kind v0.22.0 go1.20.13 linux/amd64
```

**Comment by thallgren** [comment]
I believe this was fixed by #3628, but its not yet released.

**Comment by rickyzhang82** [comment]
@thallgren,

I used v2.20.3 and still can't override the securityContext of the sidecar container.

`telepresence helm install -f values.yaml`

```
agent:
  securityContext: 
    allowPrivilegeEscalation: true
    runAsNonRoot: false
```

v2.20.3 should include the PR #3628. But it doesn't work. Please re-open the issue.

I verified that traffic manager deployment got the injected security context from the helm value.yml

```
k -n ambassador get deploy traffic-manager -o yaml
...
        - name: AGENT_SECURITY_CONTEXT
          value: '{"allowPrivilegeEscalation":true,"runAsNonRoot":false}'
...
```

~But it didn't carry all the way to the side car container in the pod:~ 
I took back my comment. I didn't see it by describe the pod but found it by get the pod.

```
k describe pod
  traffic-agent:
    Container ID:  
    Image:         ghcr.io/telepresenceio/tel2:2.20.3
    Image ID:      
    Port:          9900/TCP
    Host Port:     0/TCP
    Args:
      agent
    State:          Waiting
      Reason:       PodInitializing
    Ready:          False
    Restart Count:  0
    Readiness:      exec [/bin/stat /tmp/agent/ready] delay=0s timeout=1s period=10s #success=1 #failure=3
    Environment Variables from:
      sas-shared-config-dc6h2ft6cc                ConfigMap with prefix '_TEL_APP_A_'  Optional: false
      sas-consul-client                           Secret with prefix '_TEL_APP_A_'     Optional: false
      sas-airflow-common-properties-7b25k2m29f    ConfigMap with prefix '_TEL_APP_A_'  Optional: false
      sas-certframe-truststore-config-d25k9878hb  ConfigMap with prefix '_TEL_APP_A_'  Optional: false
    Environment:
      _TEL_APP_A_AIRFLOW__CORE__FERNET_KEY:            <set to the key 'fernet-key' in secret 'sas-airflow-fernet-key'>                      Optional: false
      _TEL_APP_A_AIRFLOW__WEBSERVER__SECRET_KEY:       <set to the key 'webserver-secret-key' in secret 'sas-airflow-webserver-secret-key'>  Optional: false
      _TEL_APP_A_AIRFLOW__CELERY__BROKER_URL:          <set to the key 'connection' in secret 'sas-airflow-broker-url-cb26kh44k5'>           Optional: false
      _TEL_APP_A_AIRFLOW__CORE__SQL_ALCHEMY_CONN:      <set to the key 'connection' in secret 'sas-airflow-metadata-fc59mhmffc'>             Optional: false
      _TEL_APP_A_AIRFLOW__DATABASE__SQL_ALCHEMY_CONN:  <set to the key 'connection' in secret 'sas-airflow-metadata-fc59mhmffc'>             Optional: false
      _TEL_APP_A_AIRFLOW_CONN_AIRFLOW_DB:              <set to the key 'connection' in secret 'sas-airflow-metadata-fc59mhmffc'>             Optional: false
      _TEL_AGENT_POD_IP:                                (v1:status.podIP)
      _TEL_AGENT_NAME:                                 sas-airflow-webserver-57746fc6-tm976 (v1:metadata.name)
      A_TELEPRESENCE_MOUNTS:                           /opt/airflow:/opt/airflow/pod_templates/pod_template_file.yaml:/opt/airflow/airflow.cfg:/opt/airflow/config/airflow_local_settings.py:/tmp:/opt/airflow/logs:/security:/opt/sas/viya/config/etc/SASSecurityCertificateFramework/cacerts:/opt/sas/viya/config/etc
```

k get pod
```
...
    securityContext:
      allowPrivilegeEscalation: true
      runAsNonRoot: false
...
```

The intercept failed in the init container -- `tel-agent-init`.  I knew you can override the security context setting at the pod level for individual container. But I can't find the doc about security context for init container..

```
telepresence intercept sas-airflow-webserver --port 8080:8080 --env-file ~/.tpenv/sas-airflow-webserver.env
telepresence intercept: error: connector.CreateIntercept: Error: container has runAsNonRoot and image will run as root (pod: "sas-airflow-webserver-7f65b4f656-qlk28_d22271(b030cb0f-f5c9-4e3f-a7a8-8b308c6abab3)", container: tel-agent-init)
Hint: if the error mentions resource quota, the traffic-agent's requested resources can be configured by providing values to telepresence helm install
```

I think the issue is related to the init container security context.

**Comment by thallgren** [comment]
@rickyzhang82 I suggest that you create a new ticket for the init-container security context. This ticket is fixed.
 
The `tel-agent-init` container runs with the hard-coded security context:
```yaml
  capabilities:
    - NET_ADMIN
```
and that capability is necessary for it to function.

**Comment by rickyzhang82** [comment]
@thallgren 

I submitted #3745. I tried to hack it with a quick and dirty fix by adding hard-coded security context. However, I have no authorization to push a new image to the registry. Are there any workaround to try on a code change locally?

**Comment by thallgren** [comment]
The workaround when the init-container fails is generally to avoid that it is needed. Please check [this section](https://www.telepresence.io/docs/troubleshooting/#injected-init-container-doesnt-function-properly) of our troubleshooting guide.
