### ISSUE TITLE
Volume mount on windows does not work

### ISSUE THREAD

**Issue by Dakror** [telepresenceio/telepresence#3715]
**Describe the bug**

Trying to get telepresence working with my cluster, i cannot get the volume mounts to work on windows. I'm using microk8s 1.29, connected into the cluster node network via wireguard. To avoid a conflict, I'm using 

`telepresence connect --kubeconfig=<kubeconfig> --proxy-via all=<workload>`

The connection is established, but no drive T is appearing with my volumes. My workload is using a cephFS-based PVC, but even with the `ignore-volume...` annotation, no drive is created (expecting the /var/run/secrets to show up at least).

Logs: 
[log.zip](https://github.com/user-attachments/files/17553330/log.zip)

From the connector logs during a disconnect-reconnect cycle, i found 

```
"C:\Program Files\SSHFS-Win\bin\sshfs-win.exe" sshfs-win cmd -ouid=-1 -ogid=-1 -F none -f -C -oConnectTimeout=10 -o follow_symlinks -o allow_root -o directport=45639 10.1.4.64:/tel_app_exports/api-service T:: exited with 1
```

which when run manually again, is invalid because of the double-mention of the command, but after removal of the error, it fails with connection refused. Might be a clue.

I've been using Bridge 2 Kubernetes, but they've announced they're archiving the project. So I'm looking for alternatives.

**To Reproduce**
1. telepresence connect
2. telepresence intercept
3. No T drive is showing up

**Expected behavior**
Expecting to find a drive either in explorer or via cmd or via the server that im trying to debug

**Versions (please complete the following information):**
 - Output of `telepresence version`
OSS Client         : v2.20.0
OSS Root Daemon    : v2.20.0
OSS User Daemon    : v2.20.0
OSS Traffic Manager: v2.20.0
Traffic Agent      : ghcr.io/telepresenceio/tel2:2.20.0

 - Operating system of workstation running `telepresence` commands
Win10 Pro 2H22 (10.0.19045)

 - Kubernetes environment and Version [e.g. Minikube, bare metal, Google Kubernetes Engine]
microk8s k8s 1.29 on bare metal, networking layer is kube-ovn, nodes are running fedora server 38 with normal amount of firewall settings

**VPN-related bugs:**
wireguard was my first guess since i couldnt access the node ssh anymore once telepresence was connected, but this was fixed with the proxy-via parameter

**Comment by thallgren** [comment]
@Dakror , I'm not able to reproduce this problem. Can you please try setting your daemon log-levels to debug, rerun the intercept, and then provide the logs again?

Create (or modify existing) `%USERPROFILE%\AppData\Roaming\telepresence\config.yml` so that it contains this:

```yaml
logLevels:
  userDaemon: debug
  rootDaemon: debug
```

**Comment by Dakror** [comment]
[logs.zip](https://github.com/user-attachments/files/17616824/logs.zip)
Here you go. Looks to me like the connection to the SFTP server in the agent pod is not able to be established.

**Comment by thallgren** [comment]
Yes, I think this is caused by an oversight in the proxy-via implementation. The mount is trying to connect using the original (cluster side) IP. It should use the proxied IP here. I'll create a regression test for this and look into how to solve it.

**Comment by Dakror** [comment]
Thank you so much for the rapid response!

**Comment by thallgren** [comment]
Fix released in version 2.20.3

**Comment by Dakror** [comment]
Thank you so much, will give it a shot tomorrow!

**Comment by Dakror** [comment]
@thallgren I've given telepresence another go using version 1.22.3 and still cannot get the mounted drive to show up. This time I'm trying it with a network-local kubernetes cluster, again the same workload using a cephfs volume.

[logs.zip](https://github.com/user-attachments/files/19887820/logs.zip)

Logs attached.

**Comment by thallgren** [comment]
Not sure what's going on here, but I don't think it's related to your `--proxy-via`. Can you please create a new ticket for this and include logs where you have enabled log-level debug in the client?
